/** Signal Foundry page: a restrained portrait-led founder profile framed as verified professional evidence. */
import { ArrowLeft, ArrowUpRight, Check, ChevronRight, GraduationCap, Lightbulb, ShieldCheck } from "lucide-react";

const expertise = ["Data analytics & reporting", "Power BI & data visualization", "Websites, apps & software", "Research & digital solutions"];

export default function Founder() {
  return <div className="founder-page">
    <header className="subpage-header"><a className="brand" href="/"><img className="brand-mark" src="/manus-storage/zorbit-mark_5e4a6e4a.png" alt="Zorbit Technology logo" /><span><b>ZORBIT</b><small>TECHNOLOGY</small></span></a><nav className="subpage-nav"><a href="/">Home</a><a href="/#services">Services</a><a href="/#work">Portfolio</a><a href="/about">About Us</a><a className="nav-cta" href="/#contact">Contact <ArrowUpRight size={15} /></a></nav></header>
    <main>
      <section className="founder-hero section-shell"><div className="subpage-nodefield founder-nodefield" aria-hidden="true"><i /><i /><i /><i /><i /><b /><b /><b /></div><div className="founder-copy"><div className="page-return"><ArrowLeft size={15} /><a href="/about">About Zorbit</a></div><span className="section-index">MEET THE FOUNDER / 01</span><h1>Musa Mubarak<br /><span>Abdulaziz.</span></h1><p className="founder-role">Founder &amp; CEO · Zorbit Technology</p><p>Musa Mubarak Abdulaziz is a technology professional working across data analytics, digital solutions, and practical product delivery. He founded Zorbit to help individuals and businesses use technology to solve real-world problems with greater clarity and confidence.</p><div className="founder-tags">{expertise.map((item) => <span key={item}>{item}</span>)}</div></div><figure className="founder-portrait"><span className="portrait-index">IDENTITY / VERIFIED / 01</span><div className="portrait-scan" aria-hidden="true" /><img src="/manus-storage/musa-mubarak-abdulaziz-founder_7d444efa.webp" alt="Musa Mubarak Abdulaziz, Founder and CEO of Zorbit Technology" /><figcaption><span>FOUNDER / CEO</span><b>MUSA MUBARAK ABDULAZIZ</b><i /></figcaption></figure></section>

      <section className="founder-background section-shell"><div className="founder-background-heading"><span className="section-index">BACKGROUND / 02</span><h2>Precision in thought.<br /><span>Usefulness in delivery.</span></h2></div><div className="founder-background-grid"><div className="education-plate"><GraduationCap size={23} /><span>EDUCATION</span><strong>Physics &amp;<br />Electronics.</strong><p>Graduate of the Air Force Institute of Technology (AFIT), Kaduna.</p></div><div className="founder-background-copy"><div className="founder-proof-rail"><span>FIELD NOTE / 02</span><i /></div><p>Musa’s academic grounding in Physics and Electronics supports a systems-oriented approach to technology: observe the problem, understand the moving parts, and build a response that works in the real world. He combines this technical discipline with hands-on experience in data analytics, Power BI, websites, applications, and digital solutions.</p><p>The operating question is simple: what will make the next decision or task clearer? That focus keeps the work grounded in useful information, dependable processes, and digital tools that clients can actually use.</p><div className="founder-credentials"><div><span>FOCUS</span><b>Data · Digital · Delivery</b></div><div><span>APPROACH</span><b>Practical, evidence-led, human</b></div></div></div></div></section>

      <section className="founder-vision section-shell"><div className="vision-mark"><Lightbulb size={25} /></div><div><span className="section-index">FOUNDER VISION / 03</span><h2>Technology should make<br /><em>possibility practical.</em></h2><p>Zorbit was founded on the belief that useful technology should not be reserved for organisations with the largest budgets. The company exists to help SMEs, businesses, and individuals across all states access understandable data, usable digital products, and dependable operational tools at fair, affordable prices.</p></div><a className="button button-primary" href="/#contact">Work with Zorbit <ArrowUpRight size={17} /></a></section>
    </main>
    <footer className="subpage-footer section-shell"><a className="brand" href="/"><img className="brand-mark" src="/manus-storage/zorbit-mark_5e4a6e4a.png" alt="Zorbit Technology logo" /><span><b>ZORBIT</b><small>TECHNOLOGY</small></span></a><span>© 2026 Zorbit Technology · Serving clients nationwide</span><a href="/#contact">Start a conversation <ChevronRight size={15} /></a></footer>
  </div>;
}
